from Affine4Game import Affine4Game
from AglCannon import AglCannon
from QuartoDataTypes import *
from depthSaver import DepthSaver
from InfoPlotting import LoadingBar
import multiprocessing
import time
import os
import lmdb
import struct
import shutil
import gc

# ------------------------------------------------------------
# HELPER for loadData
#
# Combines all solution files for a given depth into one file.
#
# Specifically, this function:
#   - Loads existing solutions from Agl_Level_<depth>_solved.txt
#   - Merges additional valid solutions from:
#       • Agl_Level_<depth>_chunk*_to_*.txt (valid only)
#       • Agl_Level_<depth>_chunk*_CudaSolved*.txt (may include partials)
#   - Ensures no duplicate solutions (preserves existing entries)
#   - Saves the final combined result into Agl_Level_<depth}_solved.txt
#
# Args:
#   folder (str): Directory containing the solution files
#   depth (int): Depth level of the solution files to combine
#
# Returns:
#   None. Saves merged solutions to disk.
# ------------------------------------------------------------
def combine_solution_files(folder, depth):
    print("Combining solution files...")
    combined_solutions = {}

    # Load existing solutions first (if they exist)
    solved_file = os.path.join(folder, f"Agl_Level_{depth}_solved.txt")
    print(f'Found solved file {solved_file}')
    if os.path.exists(solved_file):
        existing_loader = DepthSaver()
        existing_loader.loadGames(fileName=os.path.basename(solved_file), path=folder + "/")
        combined_solutions.update(dict(zip(existing_loader.hashes, existing_loader.solutions)))

    # Then, load backpropagated solutions if available
    backprop_file = os.path.join(folder, f"Agl_Level_{depth}_backprop_solved.txt")
    if os.path.exists(backprop_file):
        print(f'Found backprop file {backprop_file}')
        loader = DepthSaver()
        loader.loadGames(fileName=os.path.basename(backprop_file), path=folder + "/")
        for h, s in zip(loader.hashes, loader.solutions):
            if h not in combined_solutions:
                combined_solutions[h] = s

    # Then, load _to_ files (they only contain valid solutions)
    for file in sorted(os.listdir(folder)):
        # if file.startswith(f"Agl_Level_{depth}_chunk") and "_to_" in file: # TODO: for GPU parallelism
        if file.startswith(f"CPU_Level_{depth}_chunk") and "_to_" in file: # for CPU parallelism
            print(f'Found chunk file {file}')
            loader = DepthSaver()
            loader.loadGames(fileName=file, path=folder + "/")
            for h, s in zip(loader.hashes, loader.solutions):
                if h not in combined_solutions:
                    combined_solutions[h] = s

    # Save the merged solutions
    saver = DepthSaver()
    saver.hashes = list(combined_solutions.keys())
    saver.solutions = list(combined_solutions.values())
    saver.saveSolution(f"Agl_Level_{depth}_solved.txt", path=folder + "/")

    print(f"Merged solutions saved to {solved_file}. Total unique solved boards: {len(combined_solutions)}")

# ------------------------------------------------------------
# HELPER for loadData
#
# Loads solved board hashes and their associated solution strings
# from a .txt file (generated by DepthSaver).
# 
# Returns:
#   A dictionary mapping board hash → solution string
#   Example: {123456789: "AD2", ...}
# ------------------------------------------------------------
def parse_solutions(file_path):
    print(f"Parsing {file_path}...")
    loader = DepthSaver()
    loader.loadGames(fileName=os.path.basename(file_path), path=os.path.dirname(file_path) + "/")
    return dict(zip(loader.hashes, loader.solutions))

# ------------------------------------------------------------
# HELPER for loadData
#
# Loads all unsolved board hashes from depth input files.
# This includes:
#   - Agl_Level_<d>_unsolved.txt
#   - Agl_Level_<d>_unsolved_chunk#.txt (optional chunks)
#
# Returns:
#   A flat list of board hashes [hash1, hash2, ...]
# ------------------------------------------------------------
def load_unsolved(folder, depth):
    print("Loading unsolved files...")
    hashes = []
    base_file = os.path.join(folder, f"Agl_Level_{depth}_unsolved.txt")
    if os.path.exists(base_file):
        loader = DepthSaver()
        loader.loadGames(fileName=os.path.basename(base_file), path=os.path.dirname(base_file) + "/")
        hashes.extend(loader.hashes)

    return hashes 

# ------------------------------------------------------------
# For a given depth level load both solved boards with their 
# solution string from depth and unsolved hashes which need a 
# solution string added from depth-1.
#
# Args:
#   folder (str): Directory containing the solution files
#   depth (int): Depth level of the solution files to combine
#
# Returns:
#   A Tuple: parent_hashes (list[ints]): Unsolved board hashes
#            parent_hash_set (set(ints)): Unsolved board hashes
#            depth_solutions (dict{int:str}): Solutions containing hash and solution string at depth
#            depth_solution_hashes (set(ints)): Solution hashes at depth
# ------------------------------------------------------------
def loadData(folder, depth):
    print("Loading boards...")
    start_time = time.time()

    # Load the solved boards from depth d for all chunks in folder TODO: multi file for depths 7-4
    # combine_solution_files(folder, depth)
    # depth_solutions = parse_solutions(os.path.join(folder, f"Agl_Level_{depth}_solved.txt"))
    # depth_solution_hashes = set(depth_solutions.keys())

    # Load for depth 8 single chunk file
    for file in sorted(os.listdir(folder)):
        if file.startswith(f"CPU_Level_{depth}_chunk"):
            depth_solutions = parse_solutions(os.path.join(folder, file))
            depth_solution_hashes = set(depth_solutions.keys())

    # Load the unsolved boards from depth d-1
    parent_hashes = load_unsolved(folder, depth - 1)
    parent_hash_set = set(parent_hashes)

    end_time = time.time()
    elapsed = end_time - start_time
    print(f"\nLoading boards completed in {elapsed:.2f} seconds.")

    return (parent_hashes, parent_hash_set, depth_solutions, depth_solution_hashes)

# -----------------------------------------------------------------------------------------------
# Minimax simulation loop to recreate the solution string until 
# matching hash is found in memotable to return full solution path.
# 
# ==================== Helper Functions for Backpropagate =======================================
def traitsInCommon(p1, p2):
    commonTraits =  bin(p1 & p2).count('1')
    commonTraits += bin((p1 ^ 15) & (p2 ^ 15)).count('1')
    return commonTraits

# Finds best piece that could be placed which is invariant to 'toPlace' if the current
# pieces on the board are 'placed'
def bestPiece(game: Affine4Game, placed: list[int], toPlace:int):
    for i in range(toPlace):
        if game.remainingPieces[i] < 1:
            continue
        for n in range(len(placed)):
            # End loop early if current pieces shares a different number of traits
            # in common with the placed piece
            if traitsInCommon(i, placed[n]) != traitsInCommon(toPlace, placed[n]):
                break
        # If the loop didn't end early, return the current piece
        else:
            return i
    return toPlace

# Helper to find the score of a solution string based on whos turn it is.
def find_score(solution: str) -> int:
    if len(solution) % 2 == 0:
        print(f"Invalid score path (even length): {solution}")
        return -999

    if solution[-1] == '1':
        return 0
    if (len(solution) // 2) % 2 == 1:
        return 1
    else:
        return -1
# ==========================================================================================
def backpropagate(cannonizer, parent_hashes_chunk):
    global shared_depth_solutions, shared_remaining_solved_hashes
    parent_game = Affine4Game(undoMemLength=0)
    best_solutions = {}

    for parent_hash in parent_hashes_chunk:
        if parent_hash in best_solutions:
            continue  # Already handled as a direct match

        # Load the parent game
        parent_game.loadFromHash(parent_hash)
        best_score = -2

        tried_pieces = set()
        pieces = parent_game.getRemainingPieces()
        placed_pieces = parent_game.getPlacedPieces()
        places = parent_game.getAvaliableSquares()
        early_exit = False 
        best_path = '-'

        for piece in pieces:
            if (best_score > 0) or early_exit: break
            piece = bestPiece(parent_game, placed_pieces, piece)
            if piece in tried_pieces:
                continue
            tried_pieces.add(piece)

            if not parent_game.selectPiece(piece):
                print("Piece Selection failed.")
                continue  # Skip if piece selection failed

            for square in places:
                if best_score > 0: break
                if not parent_game.placePiece(piece, square):
                    print("Place Piece failed.")
                    continue  # Skip if placement failed

                # Canonize the resulting child board (for depths 1-7, not 7-8)
                child_game = cannonizer.cannonizeGame(parent_game)
                child_hash = child_game.hashBoard()

                # Check if this child board was solved at depth d
                if child_hash in shared_remaining_solved_hashes:
                    child_sol = shared_depth_solutions[child_hash]

                        # Encode the move that got us here
                    pieceChr = chr(piece + 64)
                    squareChr = chr((square.x << 2) + square.y + 64)
                    full_solution = pieceChr + squareChr + child_sol  # Prepend move to child's solution

                    # Save if it's a better score
                    score = find_score(full_solution)
                    if score > best_score:
                        best_path = full_solution  # Use best-scoring full path
                        best_score = score
                else:
                    early_exit = 1
                    best_path = '-'
                    break

                parent_game.removePiece(square) # Undo the move on the original parent board
            parent_game.deselectAll()  # Deselect the piece before moving to the next one

        if best_path != '-':
            best_solutions[parent_hash] = best_path

    solved_hashes = set(best_solutions.keys())
    unsolved_hashes = set(parent_hashes_chunk) - solved_hashes
    return best_solutions, unsolved_hashes

# ------------------------------------------------------------
# 
# ------------------------------------------------------------
def convert_txt_to_lmdb_binary_keys(txt_path, lmdb_path):
    os.makedirs(os.path.dirname(lmdb_path), exist_ok=True)
    env = lmdb.open(lmdb_path, map_size=5 * 1024**3)  # Up to 1TB

    with env.begin(write=True) as txn, open(txt_path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or ',' not in line:
                continue
            key_str, value = line.split(',', 1)
            try:
                key_int = int(key_str)
                key_bytes = struct.pack('>Q', key_int)
                txn.put(key_bytes, value.encode('ascii'))
            except ValueError:
                continue  # Skip malformed lines

    env.sync()
    print(f"LMDB written to {lmdb_path} with binary 8-byte keys.")

class LMDBSolutionDict:
    def __init__(self, path):
        self.env = lmdb.open(path, readonly=True, lock=False, max_readers=2048)
        self.txn = self.env.begin()

    def __getitem__(self, key: int) -> str:
        key_bytes = struct.pack('>Q', key)
        val = self.txn.get(key_bytes)
        if val is None:
            raise KeyError(key)
        return val.decode('ascii')

    def __contains__(self, key: int) -> bool:
        key_bytes = struct.pack('>Q', key)
        return self.txn.get(key_bytes) is not None

    def get(self, key: int, default=None) -> str:
        key_bytes = struct.pack('>Q', key)
        val = self.txn.get(key_bytes)
        return val.decode('ascii') if val else default

class LMDBSet:
    def __init__(self, path):
        self.env = lmdb.open(path, readonly=True, lock=False)
        self.txn = self.env.begin()

    def __contains__(self, key: int) -> bool:
        key_bytes = struct.pack('>Q', key)
        return self.txn.get(key_bytes) is not None

# ------------------------------------------------------------
# 
# ------------------------------------------------------------
def init_worker(depth_lmdb_path, remaining_lmdb_path):
    global shared_depth_solutions, shared_remaining_solved_hashes
    shared_depth_solutions = LMDBSolutionDict(depth_lmdb_path)
    shared_remaining_solved_hashes = LMDBSet(remaining_lmdb_path)

# ------------------------------------------------------------
# 
# ------------------------------------------------------------
def workerListConstructor(values, startIndex, numWorkers, numPerWorker):
    results = []
    index = startIndex
    for i in range(numWorkers):
        workerValues = []
        for n in range(numPerWorker):
            if index >= len(values):
                if len(workerValues) > 0:
                    results.append(workerValues)
                return results, index - startIndex
            workerValues.append(values[index])
            index += 1
        results.append(workerValues)
    return results, index - startIndex

# Test multi-folder backprop
def make_test_multi():
    base_folder = "./test"
    test_folders = [
        "test_chunk1",
        "test_chunk2",
        "test_chunk3"
    ]

    # Step 1: Create folders
    for folder in test_folders:
        os.makedirs(os.path.join(base_folder, folder), exist_ok=True)

    # Step 2: Create fake solved files with distinct ranges
    ranges = {
        "test_chunk1": range(1000, 2000),
        "test_chunk2": range(2000, 3000),
        "test_chunk3": range(3000, 4000)
    }

    for folder, hash_range in ranges.items():
        file_path = os.path.join(base_folder, folder, "CPU_Level_8_chunk0_to_10.txt")
        with open(file_path, "w") as f:
            for h in hash_range:
                f.write(f"{h},AD1\n")

    # Step 3: Create initial unsolved file in folder 1 with all hashes (1000–3999)
    initial_unsolved_path = os.path.join(base_folder, "test_chunk1", "Agl_Level_7_unsolved.txt")
    with open(initial_unsolved_path, "w") as f:
        for h in range(1000, 4000):
            f.write(f"{h},-\n")

# ------------------------------------------------------------
# Connect Solutions Parallelized (any depth to depth-n)
#
# Main backpropagation driver that processes all levels from
# deepest_depth down to shallowest_depth.
#
# At each depth level d:
#   - Loads solved boards from Agl_Level_d_solved.txt
#   - Loads parent hashes from depth d-1 unsolved files
#   - Matches child to parent in two phases:
#       1. Direct hash match
#       2. Simulated children via piece/square moves + canonization
#   - Backpropagates the best child solution string (lowest score)
#     to the parent board hash at depth d-1
#
# Results:
#   - Saves backpropagated solutions: Agl_Level_<d-1>_backprop_solved.txt
#   - Saves unmatched solved hashes: Agl_Level_<d>_orphans.txt
# ------------------------------------------------------------
if __name__ == "__main__":
    # Test folders for test multi
    # make_test_multi()
    # folders = ["./test/test_chunk1",
    #            "./test/test_chunk2",
    #            "./test/test_chunk3"]
    
    # Folders for chunk back to back no interupt
    folders = ["./Solved_Unsolved/backprop_level_8_solved_files",            
               "./Solved_Unsolved/backprop_level_8_chunk1_to_9_solved_files", 
               "./Solved_Unsolved/backprop_level_8_chunk2_to_9_solved_files",
               "./Solved_Unsolved/backprop_level_8_chunk3_to_9_solved_files",
               "./Solved_Unsolved/backprop_level_8_chunk4_to_9_solved_files",
               "./Solved_Unsolved/backprop_level_8_chunk1_to_10_solved_files"]

    # Folder for depths 7-4
    # folder    = "./Solved_Unsolved"
    os.makedirs("lmdb_store", exist_ok=True)

    deepest_depth       = 8
    shallowest_depth    = 7
    numWorkers          = 4
    numPerWorkerBackprop = 1000
    cannonizer          = AglCannon()
    # start_time          = time.time()
    first_folder = False

    for folder in folders:
        start_time = time.time()
        log_path = os.path.join(folder, "backprop_log.txt")
        with open(log_path, "w") as log_file:
            if first_folder:
                first_folder = False
                break
            
            # Work backward from the deepest depth down to the shallowest one (inclusive)
            for depth in range(deepest_depth, shallowest_depth, -1):
                print(f"\nBackpropagating from depth {depth} to depth {depth-1}...")

                # Load data
                (parent_hashes, parent_hash_set_local, depth_solutions_local, depth_solution_hashes_local) = loadData(folder, depth)

                # This dictionary will contain the completed solution to backpropagating the solution strings
                combined_best_solutions = {}
            
                # Direct Matches (identical hash in both depths)
                direct_matched_local = depth_solution_hashes_local.intersection(parent_hash_set_local)
                match_summary = (
                    f"\nMatch Breakdown:\n"
                    f"Direct matches     : {len(direct_matched_local)}\n"
                    f"Require simulation : {len(parent_hash_set_local) - len(direct_matched_local)}\n"
                    f"Total parent boards: {len(parent_hash_set_local)}\n"
                )
                print(match_summary)
                log_file.write(match_summary)
                for direct_hash in direct_matched_local:
                    child_sol = depth_solutions_local[direct_hash]

                    # Save first and highest best score
                    score = find_score(child_sol) 
                    if (direct_hash not in combined_best_solutions) or score > find_score(combined_best_solutions[direct_hash]) : 
                        combined_best_solutions[direct_hash] = child_sol  # Use best scoring solution

                # Generate children from unmatched parent boards
                remaining_solved_hashes = depth_solution_hashes_local - direct_matched_local
                parent_hash_set_local, depth_solution_hashes_local, = None, None

                print(f"Direct hashes took {time.time() - start_time}s.")
                if folder == "./Solved_Unsolved/backprop_level_8_solved_files":
                    # Compute unsolved for direct-only folders
                    unsolved = set(parent_hashes) - direct_matched_local
                    if unsolved:
                        dummy_sols = ['-' for _ in unsolved]
                        saver = DepthSaver()
                        saver.hashes = list(unsolved)
                        saver.solutions = dummy_sols
                        saver.saveSolution(f"Agl_Level_{depth-1}_unsolved_childless.txt", path=folder + '/')
                        print(f"(Direct only) {len(unsolved)} parent boards remained unsolved and saved as Agl_Level_{depth-1}_unsolved_childless.txt.")

                    end_time = time.time()
                    elapsed = end_time - start_time
                    percent = ((len(combined_best_solutions)/len(parent_hashes))*100)
                    summary = (
                        f"\nBackpropagation completed in {elapsed:.2f} seconds.\n"
                        f"Depth {depth} backprop solved: {len(combined_best_solutions)}, "
                        f"backprop unsolved: {len(unsolved)}, reduction {percent:.2f}%\n"
                    )
                    print(summary)
                    log_file.write(summary)

                    first_folder = True
                    break
                print("Writing data to lmbd...")

                # Write depth_solutions_local to LMDB
                depth_sols_lmdb_path = f"lmdb_store/Agl_Level_{depth}.lmdb"
                with open(f"{depth_sols_lmdb_path}.tmp.txt", "w") as f:
                    for h, s in depth_solutions_local.items():
                        f.write(f"{h},{s}\n")
                convert_txt_to_lmdb_binary_keys(f"{depth_sols_lmdb_path}.tmp.txt", depth_sols_lmdb_path)

                # Write remaining_solved_hashes to LMDBSet
                remaining_solved_lmdb_path = f"lmdb_store/Agl_Level_{depth}_remaining_hashes.lmdb"
                with open(f"{remaining_solved_lmdb_path}.tmp.txt", "w") as f:
                    for h in remaining_solved_hashes:
                        f.write(f"{h},1\n")  # dummy value just to create the key
                convert_txt_to_lmdb_binary_keys(f"{remaining_solved_lmdb_path}.tmp.txt", remaining_solved_lmdb_path)

                depth_solutions_local, depth_solution_hashes_local = None, None
                print(f"lmdb took {time.time() - start_time}s.")
                print("Starting workers...")

                unsolved = set()
                currIndex = 0
                while currIndex < len(parent_hashes):
                    indices, diff = workerListConstructor(parent_hashes, currIndex, numWorkers, numPerWorkerBackprop)
                    with multiprocessing.Pool(processes=len(indices), initializer=init_worker, initargs=(depth_sols_lmdb_path, remaining_solved_lmdb_path)) as pool:
                        results = pool.starmap(backpropagate, [(cannonizer, indices[i],) for i in range(len(indices))])
                        for (currSolved, currUnsolved) in results:
                            print(f"Workers solved {len(currSolved)} boards, missed {len(currUnsolved)}")
                            for ele in currUnsolved:
                                unsolved.add(ele)
                            for key in currSolved.keys():
                                if key not in combined_best_solutions:
                                    combined_best_solutions[key] = currSolved[key]
                    currIndex += diff
                    elapsed = time.time() - start_time
                    print(f'Explored hashes up to {currIndex}, a total of {currIndex / len(parent_hashes) * 100 :0.3f}% | Elapsed: {elapsed:.1f}s', end="\r")
                    print()
                print()

                print(f"Simulation took {time.time() - start_time}s.")

                # Save parent boards at depth d-1 without any matching solved child
                unsolved -= direct_matched_local
                if unsolved:
                    dummy_sols = ['-' for _ in unsolved]
                    saver = DepthSaver()
                    saver.hashes = list(unsolved)
                    saver.solutions = dummy_sols
                    saver.saveSolution(f"Agl_Level_{depth-1}_unsolved_childless.txt", path=folder + '/')
                    print(f"{len(unsolved)} parent boards remained unsolved and saved as Agl_Level_{depth-1}_unsolved_childless.txt.")

                # Save Solutions at Each Depth
                if combined_best_solutions:
                    saver = DepthSaver()
                    saver.hashes = list(combined_best_solutions.keys())
                    saver.solutions = list(combined_best_solutions.values())
                    saver.saveSolution(f"Agl_Level_{depth-1}_backprop_solved.txt", path=folder + '/')
                    print(f"  {len(combined_best_solutions)} parent boards solved and saved.")

                end_time = time.time()
                elapsed = end_time - start_time
                percent = ((len(combined_best_solutions)/len(parent_hashes))*100)
                summary = (
                    f"\nBackpropagation completed in {elapsed:.2f} seconds.\n"
                    f"Depth {depth} backprop solved: {len(combined_best_solutions)}, "
                    f"backprop unsolved: {len(unsolved)}, reduction {percent:.2f}%\n"
                )
                print(summary)
                log_file.write(summary)

                # Explicit cleanup
                del parent_hashes, parent_hash_set_local, depth_solutions_local, depth_solution_hashes_local
                del combined_best_solutions, unsolved
                gc.collect()

        # Copy childless file to the next folder (if any)
        current_index = folders.index(folder)
        if current_index + 1 < len(folders):
            next_folder = folders[current_index + 1]
            src_file = os.path.join(folder, f"Agl_Level_{shallowest_depth}_unsolved_childless.txt")
            dest_file = os.path.join(next_folder, f"Agl_Level_{shallowest_depth}_unsolved.txt")
            
            if os.path.exists(src_file):
                shutil.copy(src_file, dest_file)
                print(f"Copied childless file from {folder} to {next_folder}")
            else:
                print(f"No childless file found in {folder} to copy forward.")

       



    # # Combine all depth 8 backprop files for all chunk folders
    # output_file = './test/backprop_8_solved_all.txt'
    # combined = {}
    # for folder in folders:
    #     file_path = os.path.join(folder, "Agl_Level_7_backprop_solved.txt")
    #     if os.path.exists(file_path):
    #         with open(file_path, 'r') as f:
    #             for line in f:
    #                 if ',' in line:
    #                     key, value = line.strip().split(',', 1)
    #                     combined[int(key)] = value  # avoid duplicates
    #     else:
    #         print(f"File not found: {file_path}")

    # with open(output_file, 'w') as f:
    #     for key in sorted(combined.keys()):
    #         f.write(f"{key},{combined[key]}\n")

    # print(f"Combined {len(combined)} entries into {output_file}")